import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class PlanetsDataImagesService {
  planetsImages: object = {
    'Alderaan': 'Planet_1',
    'Yavin IV' : 'Planet_2',
    'Hoth': 'Planet_3',
    'Dagobah': 'Planet_4',
    'Bespin': 'Planet_5',
    'Endor': 'Planet_6',
    'Naboo': 'Planet_7',
    'Coruscant': 'Planet_8',
    'Kamino': 'Planet_9',
    'Geonosis': 'Planet_10',
    'Utapau': 'Planet_11',
    'Mustafar': 'Planet_12',
    'Kashyyyk': 'Planet_13',
    'Polis Massa' : 'Planet_14',
    'Mygeeto': 'Planet_15',
    'Felucia': 'Planet_16',
    'Cato Neimoidia': 'Planet_17',
    'Saleucami': 'Planet_18',
    'Stewjon': 'Planet_19',
    'Eriadu': 'Planet_20',
    'Corellia': 'Planet_21',
    'Rodia': 'Planet_22',
    'Nal Hutta': 'Planet_23',
    'Dantooine': 'Planet_24',
    'Bestine IV' : 'Planet_25,
    'Ord Mantell': 'Planet_26',
    'unknown': 'Planet_27',
    'Trandosha': 'Planet_28',
    'Socorro': 'Planet_29',
    'Mon Cala': 'Planet_30',
    'Chandrila': 'Planet_31',
    'Sullust': 'Planet_32',
    'Toydaria': 'Planet_33',
    'Malastare': 'Planet_34',
    'Dathomir': 'Planet_35',
    'Ryloth': 'Planet_36',
    'Aleen Minor' : 'Planet_37',
    'Vulpter': 'Planet_38',
    'Troiken': 'Planet_39',
    'Tund': 'Planet_40',
    'Haruun Kal' : 'Planet_41,
    'Cerea': 'Planet_42',
    'Glee Anselm' : 'Planet_43',
    'Iridonia': 'Planet_44',
    'Tholoth': 'Planet_45',
    'Iktotch': 'Planet_46',
    'Quermia': 'Planet_47',
    'Dorin': 'Planet_48',
    'Champala': 'Planet_49',
    'Mirial': 'Planet_50',
    'Serenno': 'Planet_51',
    'Concord Dawn' : 'Planet_52,
    'Zolan': 'Planet_53',
    'Ojom': 'Planet_54',
    'Skako': 'Planet_55',
    'Muunilinst': 'Planet_56',
    'Shili': 'Planet_57',
    'Kalee': 'Planet_58',
    'Umbara': 'Planet_59',
    'Tatooine': 'Planet_60',
    'Jakku': 'Planet_61'

  };

  constructor() { }
}
